refactor: fragmenation and rename WebType and WebLogic #14
gKrokod/webServer pull request #18
Opened 2024-12-10 08:31 UTC by gKrokod

2024-12-10 09:03 UTC, olgaklimenko requested changes

2024-12-10 09:03 UTC, olgaklimenko commented on src/Web/WebUtils.hs
> +module Web.WebUtils (getBody, response403, response400, response404, response200, response500, mkGoodResponse, mkResponseForImage, response404WithImage) where
Папка Web, поэтому не нужно повторять слово Web в названии файла

2024-12-10 09:23 UTC, roman-bodavskiy commented on src/Web/DTO.hs
>  data UserToWeb = UserToWeb
вот это не сделано:

> 2. Разделить типы для входных/выходных данных на файлы по отношению к сущностям

например вот так:
Web.DTO.News
Web.DTO.Category
Web.DTO.User

или как-то на твое усмотрение

2024-12-11 10:42 UTC, olgaklimenko approved these changes

2024-12-11 10:48 UTC, merged