refactor : replace type with newtype
gKrokod/webServer pull request #4
Opened 2024-09-27 13:33 UTC by gKrokod

Это бы босс issue.

2024-09-27 15:24 UTC, olgaklimenko requested changes

2024-09-27 15:24 UTC, olgaklimenko commented on .gitignore
> +quickfix
Ты тулзу написал чтобы тайпы на ньютайпы заменить, или что это? Вдруг мне тоже пригодится :)

2024-09-27 15:24 UTC, olgaklimenko commented on src/Types.hs
> +data NewsOut = MkNewsOut Title UTCTime Name [Label] Content [URI_Image] Bool
record syntax, please. Без рекордов это не особо отличается от того, когда мы кучу аргументов передаём

2024-09-28 07:38 UTC, gKrokod commented on .gitignore
> +quickfix
Ненене. Я не такой продвинутый. report.hmtl от hlint и quickfix от ghcid.

2024-10-01 05:32 UTC, olgaklimenko commented on .gitignore
> +quickfix
Поняла) Спасибо!

2024-10-01 07:40 UTC, roman-bodavskiy commented on src/Base/Base.hs
> +pullAllNews connString configLimit (MkOffset userOffset) (MkLimit userLimit) columnType sortOrder mbFind filters = do
Внутри тела функции таже можно использовать `Limit`, `Offset`. Распаковывать только когда нам нужно работать именно с числом. Именно так достигается типобезопасность, мы не можем перепутать `Limit`, `Offset` с другими числами в нашей бизнес логике. Можно пойти еще дальше и определить инстанс `Num` для ньютайпа, тогда можно будет делать арифметические операции (но это уже по желанию, стратегии дерайва изучаются только на втором джуне)
```
newtype Limit = MkLimit {getLimit :: Int}
  deriving newtype Num
```

2024-10-01 07:43 UTC, roman-bodavskiy commented on src/Base/Base.hs
> +          (MkTitle title)
здесь лучше использовать рекорды, как Оля написала

2024-10-01 07:53 UTC, roman-bodavskiy requested changes

2024-10-01 07:53 UTC, roman-bodavskiy commented on src/Base/Base.hs
> +putNews pginfo (MkTitle title) time (MkLogin login) (MkLabel label) (MkContent content) images ispublish =
`keyNews <- insert $ News title time keyUsr keyCat content ispublish`
То же самое, ты вроде бы используешь ньютайпы, но они ничего не дают в плане безопасности. Ты все так же можешь перепутать все значения между собой. Плюс к тому же ты не используешь рекорды, поэтому перепутать еще проще. То есть например если ты поменяешь местами какие нибудь два текстовых поля в `News` , код скомпилируется нормально, но мы получим баг

2024-10-01 10:45 UTC, olgaklimenko requested changes

2024-10-01 10:45 UTC, olgaklimenko commented on src/Base/Base.hs
>  putNews pginfo title time login label content images ispublish =
Я думаю тут вот еще какая проблема с типами:

В текущем коде функции принимают разрозненные аргументы (например, в putNews), вместо того чтобы работать с единой сущностью (entity). Это приводит к тому, что теряется связь между данными, и появляется дублирование кода, где эти данные передаются между функциями как отдельные параметры. 

Как это можно сделать:
1) Все свойства, которые сейчас передаются как отдельные аргументы, можно объединить в одну сущность (все, что есть в News - положить в тип News и работать только с ним). 

2) Для каждой сущности может быть несколько представлений, в зависимости от контекста:
Данные от пользователя (например, запрос от пользователя - NewsRequestData)
Внутреннее представление для бизнес-логики (когда данные обрабатываются - News)
Ответ пользователю (например, формат данных, возвращаемый в API - NewsResponseData)
Соответственно, стоит создать функции для преобразования одной формы сущности в другую там, где это необходимо.

Когда все функции будут работать с одной сущностью проблема с неиспользованием newtype отпадет во многих местах, так как обёртки типов будут иметь смысл внутри сущностей. И думаю, должно появиться желание использовать рекорд синтаксис для описания сущностей.

2024-10-02 06:51 UTC, roman-bodavskiy approved these changes

2024-10-03 02:17 UTC, olgaklimenko approved these changes

2024-10-03 15:11 UTC, gKrokod commented on src/Base/Base.hs
>  putNews pginfo title time login label content images ispublish =
Провел исправления.

2024-10-04 03:26 UTC, olgaklimenko approved these changes

2024-10-04 09:34 UTC, merged