Separating code into more modules #3
gKrokod/webServer pull request #5
Opened 2024-10-06 12:02 UTC by gKrokod

Изменил структуру. Тесты пока не делал, потому что при изменении структуры очень много поплыло там и может поплыть дальше. Предлагаю пока согласовать третий вопрос без тестов, а потом я коммитом добавлю их доработку.

2024-10-07 07:16 UTC, roman-bodavskiy commented on src/Handlers/Base/Category/Create/Api.hs
> +module Handlers.Base.Category.Create.Api (createCategoryBase) where
Кажется создавать везде папки с единственным модулем `Api.hs` слегка избыточным. Ведь тут не предполагаются никакие другие модули?
Можно упростить `Handlers.Base.Category.CreateApi `или `Handlers.Base.Category.Create`

2024-10-07 07:23 UTC, roman-bodavskiy commented on src/Base/Base.hs
> -            from $
Этот модуль также нуждается в разделении. Ведь здесь все запросы ко всем тиаблицам: `news`, `category`, `users`  и т д.
Запросы должны быть примерно в таких модулях `Queries.User`, `Queries.News` и т. д., но не в `Base.Base`.
`Base.Base` может это все импортировать и собирать `Handle` (то что у тебя сделано в `Main`)

2024-10-11 07:06 UTC, olgaklimenko commented on src/Base/Base.hs
> -            from $
И переименоать надо в Database,чтобы был не просто "Базовый модуль", а "модуль для работы с базой данных"

2024-10-13 11:51 UTC, gKrokod commented
Добавил тесты под новую структуру.

2024-10-14 03:04 UTC, olgaklimenko requested changes

2024-10-14 03:04 UTC, olgaklimenko commented on test/Handlers/Database/Category/CreateSpec.hs
> +{-# LANGUAGE TemplateHaskell #-}
Тесты для логики эндпоинтов лежат в директории Database, это же ошибка?

2024-10-14 05:52 UTC, roman-bodavskiy commented on app/Main.hs
>  import Scheme (ColumnType (..), SortOrder (..))
Если имеется в виду схема бд, то она обычно называется `Schema`

2024-10-14 05:52 UTC, roman-bodavskiy commented on app/Main.hs
> +-- import qualified Database.Crypto
лишние комменты

2024-10-14 05:53 UTC, roman-bodavskiy commented on src/Handlers/Web/Base.hs
> +  { clienAdminToken :: Maybe (Proxy 'AdminRole),
опечатка clientAdminToken

2024-10-14 05:54 UTC, roman-bodavskiy commented on test/Handlers/LoggerSpec.hs
> +
лишняя строка

2024-10-14 06:09 UTC, roman-bodavskiy commented on src/Handlers/Database/Authorization.hs
> +    Right (Just (User _ _ _ _ a p)) -> do
Не отсносится к этому ПРу, но здесь неочевидно, что такое `a` `p`, и код нужно будет постоянно переписывать при каждом изменении филдов в типе `User`. Вообще код, который зависит от порядка филдов в типе не очень безопасен, легко можно перепутать эти два филда. Можно сделать так
```
Right (Just user) -> do
  let isAdmin' = isAdmin user
  let isPublisher' = isPublisher user
  ...
```

Или использовать `RecordWildCards`
```
Right (Just User {isAdmin, isPublisher}) -> do
  ...
```

2024-10-14 06:13 UTC, roman-bodavskiy approved these changes

2024-10-14 12:24 UTC, gKrokod commented on src/Handlers/Database/Authorization.hs
> +    Right (Just (User _ _ _ _ a p)) -> do
Поправил

2024-10-14 12:24 UTC, gKrokod commented on test/Handlers/LoggerSpec.hs
> +
Поправил

2024-10-14 12:24 UTC, gKrokod commented on src/Handlers/Web/Base.hs
> +  { clienAdminToken :: Maybe (Proxy 'AdminRole),
Поправил

2024-10-14 12:24 UTC, gKrokod commented on app/Main.hs
> +-- import qualified Database.Crypto
Поправил

2024-10-14 12:24 UTC, gKrokod commented on app/Main.hs
>  import Scheme (ColumnType (..), SortOrder (..))
Поправил

2024-10-14 12:24 UTC, gKrokod commented on test/Handlers/Database/Category/CreateSpec.hs
> +{-# LANGUAGE TemplateHaskell #-}
Поправил.

2024-10-15 00:58 UTC, olgaklimenko approved these changes

2024-10-15 08:34 UTC, merged