chore: add manual migrations
gKrokod/webServer pull request #6
Opened 2024-10-20 12:34 UTC by gKrokod

2024-10-21 07:19 UTC, roman-bodavskiy commented on src/Schema.hs
> +import Database.Migrations.Migrationv0 (Category (..), EntityField (..), Image (..), ImageBank (..), News (..), Password (..), Unique (..), User (..))
Вот эта зависимость мне кажется неправильной.
Получается структура таблиц по всему приложению у тебя берется из нулевой миграции. Вернемся к моему примеру, допустим нам нужно добавить столбец `lastName` в таблицу `User`. В твоей структуре нужно изменить нулевую миграцию, но это неверно, так как она уже была применена к базе данных в продакшне, и ее менять нельзя.
`module Schema` должен содержать текущую структура бд, после применения всех миграций. 
`module Database.Migrations.Migrationv0` это начальная структуа, до применения всех миграций
В таком случае ты легко сможешь добавить `Migrationv4` со столбцом `lastName`, все предыдущие миграции останутся неизменными, а структура в модуле `Schema` поменяется, так как этот модуль содержит актуальную структуру

2024-10-21 07:24 UTC, roman-bodavskiy requested changes

2024-10-21 07:24 UTC, roman-bodavskiy commented on src/Database/Migrations/Migrationv1.hs
> + TestMigrate
Ты создал новую таблицу, это не совсем то, что требуется, давай попробуем добавить столбец`lastName` в существующую таблицу `user`, так чтобы не удалить существующих пользователей
Для уже существующих пользователей пусть будет `lastName = name`
Это очень частая задача на реальном проекте, добавить столбец в бд, не удаляя существующие данные

2024-10-21 07:26 UTC, roman-bodavskiy commented on app/Main.hs
>    run 4221 $ authorization serverSetup app
кстати, почему у тебя порт захардкожен, он же вроде в конфиге есть?

2024-10-21 10:38 UTC, gKrokod commented on app/Main.hs
>    run 4221 $ authorization serverSetup app
поправил

2024-10-21 10:38 UTC, gKrokod commented on src/Database/Migrations/Migrationv1.hs
> + TestMigrate
добавил такую ситуацию

2024-10-21 13:39 UTC, roman-bodavskiy commented on src/Database/Data/TestImage.hs
> +-- import Schema (Image (..))
лишний коммент

2024-10-21 13:47 UTC, roman-bodavskiy commented on src/Database/Verb.hs
> +insertTestData :: ConnectionString -> IO (Either SomeException Success)
у тебя эта функция не используется, так как ты переместил эту логику в миграцию 4

2024-10-21 13:50 UTC, roman-bodavskiy commented on src/Database/Migrations/Migration.hs
> +  is <- isMigrateTable pginfo
не очень понятное имя переменной `is`

2024-10-22 10:03 UTC, gKrokod commented on src/Database/Data/TestImage.hs
> +-- import Schema (Image (..))
поправил

2024-10-22 10:03 UTC, gKrokod commented on src/Database/Verb.hs
> +insertTestData :: ConnectionString -> IO (Either SomeException Success)
поправил

2024-10-22 10:03 UTC, gKrokod commented on src/Database/Migrations/Migration.hs
> +  is <- isMigrateTable pginfo
поправил

2024-10-22 12:05 UTC, roman-bodavskiy approved these changes

2024-10-22 12:44 UTC, merged